### ISSUE TITLE
iFrame reference implementation doesn't support uspapiLocator

### ISSUE THREAD

**Issue by HeinzBaumann** [InteractiveAdvertisingBureau/CCPA-reference-code#13]
The IAB reference implementation of the USP API does not create a “__uspapiLocator” iframe to support the case where the the USP CMP is loaded in a parent iframe of the iframe containing quant.js. This effectively means that the ref impl, as is, does not support communication across iframes (even though it is capable of receiving messages via `postMessage`).

**Comment by dmdabbs** [comment]
Yes, FWIW here's the iframe creator code adapted from GDPR TCF "stub"

`        function addFrame() {
          if (!window.frames['__uspapiLocator']) {
            if (document.body) {
              var iframe=document.createElement('iframe');
              iframe.style = 'display:none';
              iframe.name = '__uspapiLocator';
              iframe.width=0;
              iframe.height=0;
              document.body.appendChild(iframe);
         } else {
              // In the case where this stub is located in the head,
              // this allows us to inject the iframe more quickly than
              // relying on DOMContentLoaded or other events.
              setTimeout(addFrame, 2);
            }
          }
        }
        addFrame();
`

**Comment by smozhaiskyi-rubi** [comment]
Seems to be done by https://github.com/InteractiveAdvertisingBureau/CCPA-reference-code/pull/17

**Comment by HeinzBaumann** [comment]
Reviewed and merged into master.
