### ISSUE TITLE
cross iframe communication requests plain JS vs JSON

### ISSUE THREAD

**Issue by HeinzBaumann** [InteractiveAdvertisingBureau/CCPA-reference-code#14]
For communication across iframes, the IAB reference implementation expects a plain JavaScript object to be passed as data via `postMessage`. This differs from the GDPR CMP implementation which expects the object to be serialized as a JSON string.

**Comment by dmdabbs** [comment]
@HeinzBaumann does this require any change in the specs or just in the code here to expect a string that is parsed?

**Comment by HeinzBaumann** [comment]
I think this is code change only.

**Comment by skedastik** [comment]
@HeinzBaumann @dmdabbs It isn't a problem per se that the implementation differs from the GDPR CMP. I was just pointing it out as an observation. This would in fact require a change in both the code and the spec. I'd say leave the spec and implementation as is.

**Comment by HeinzBaumann** [comment]
I talked to my developer it is just a difference between the two implementation. We don't need to a change here.
