### ISSUE TITLE
Cross-origin iframes communication issue 

### ISSUE THREAD

**Issue by HeinzBaumann** [InteractiveAdvertisingBureau/CCPA-reference-code#15]
The IAB reference implementation of the USP API has a flaw that will prevent communication across cross-origin iframes. It does not supply a target origin argument of “*” to its call to `window.postMessage`.

**Comment by smozhaiskyi-rubi** [comment]
OK, working on this.

**Comment by HeinzBaumann** [comment]
Reviewed the code change and merged it into master.
