### ISSUE TITLE
us_privacy vs usprivacy for cookie name

### ISSUE THREAD

**Issue by elgreg** [InteractiveAdvertisingBureau/CCPA-reference-code#19]
Is there a reason that the cookie is set with the name "us_privacy" here https://github.com/InteractiveAdvertisingBureau/CCPA-reference-code/blob/master/src/uspapi.js#L43 but that in the documentation in the [v1 spec](https://iabtechlab.com/wp-content/uploads/2019/11/US-Privacy-USER-SIGNAL-API-SPEC-v1.0.pdf) says the cookie should be named "usprivacy" without the underscore?

**Comment by dmdabbs** [comment]
Agree that reference code should track with the spec unless there;s good reason to do otherwise.

**Comment by HeinzBaumann** [comment]
Thank you for spotting this. I do a PR right away.

**Comment by HeinzBaumann** [comment]
Change is committed to master.
